services:
  user-data-local:
    image: user-data-app
    environment:
      MT4_PASSWORD: ${MT4_PASSWORD}
      MT5_PASSWORD: ${MT5_PASSWORD}
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "3839:3838"
    volumes:
      - ../../source/user-data-App/configDocker:/app/configDocker:ro
    restart: unless-stopped
