services:
  aggr-data-local:
    image: aggr-data-app
    environment:
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "3838:3838"
    volumes:
      - ../../source/aggr-data_App/configDocker:/app/configDocker:ro
    restart: unless-stopped

