services:
  negative-equity-local:
    image: negative-equity
    environment:
      MT4_PASSWORD: ${MT4_PASSWORD}
      MT5_PASSWORD: ${MT5_PASSWORD}
      PG_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ../../source/negative-equity/configDocker:/app/configDocker:ro
      - ../../source/negative-equity/dataDocker:/app/dataDocker:rw
    restart: "no"

