name: release-dockerhub

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Which image to build (use 'all' to build every variant)"
        type: choice
        required: true
        options:
          - all
          - big-trades
      tag:
        description: "Image tag (e.g. v1.2.3). If empty, short SHA is used."
        required: false
  release:
    types: [published]

permissions:
  contents: read

env:
  # Final image name on Docker Hub; override via repo Variable IMAGE_NAME if needed
  IMAGE: ${{ vars.IMAGE_NAME || format('{0}/tt-reporting', secrets.DOCKERHUB_USERNAME) }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Each entry is one Dockerfile/variant
          - name: big-trades
            dockerfile: build/Dockerfile.big-trades   # <-- must be an actual file
            context: .
            suffix: big-trades
            platforms: linux/amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute base tag
        id: tag
        shell: bash
        run: |
          # Decide the base tag in pure Bash:
          # - release event → use the release tag (e.g. v1.2.3)
          # - manual run with input → use inputs.tag
          # - otherwise → short SHA tag
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "value=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [[ -n "${{ inputs.tag }}" ]]; then
            echo "value=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      # Optional: explicit skip log for non-selected variants on manual runs
      - name: Maybe skip this variant
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.variant != 'all' && matrix.name != inputs.variant }}
        run: echo "Skipping variant: ${{ matrix.name }} (selected: ${{ inputs.variant }})"

      - name: Build & Push
        if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && (inputs.variant == 'all' || matrix.name == inputs.variant)) }}
        uses: docker/build-push-action@v6
        with:
          context:   ${{ matrix.context }}
          file:      ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ env.IMAGE }}:${{ steps.tag.outputs.value }}-${{ matrix.suffix }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

      - name: Echo published image
        if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && (inputs.variant == 'all' || matrix.name == inputs.variant)) }}
        run: echo "Pushed: ${{ env.IMAGE }}:${{ steps.tag.outputs.value }}-${{ matrix.suffix }}"
