name: release-dockerhub

on:
  # Manual button in the Actions tab
  workflow_dispatch:
    inputs:
      variant:
        description: "Which image to build (use 'all' to build every variant)"
        type: choice
        required: true
        options:
          - all
          - big-trades
          # add more names here; keep in sync with matrix.include below
      tag:
        description: "Image tag (e.g. v1.2.3). If empty, short SHA is used."
        required: false

  # Auto-run when a Release is published (not draft)
  release:
    types: [published]

permissions:
  contents: read

env:
  # Final image name on Docker Hub; override with repo Variable IMAGE_NAME if needed
  IMAGE: ${{ vars.IMAGE_NAME || format('{0}/tt-reporting', secrets.DOCKERHUB_USERNAME) }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    # --- Run this job only for:
    #     - release event (build ALL variants)
    #     - manual run with variant=='all'
    #     - manual run with variant matching the matrix.name
    if: >
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' &&
       (inputs.variant == 'all' || matrix.name == inputs.variant))

    strategy:
      fail-fast: false
      matrix:
        include:
          # Each entry is one Dockerfile/variant
          - name: big-trades
            dockerfile: build/big-trades
            context: .
            suffix: r-ver
            platforms: linux/amd64
          # ...add ~7 more variants the same way...

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Store these as repo Secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute base tag
        id: tag
        shell: bash
        run: |
          # Decide the base tag purely in Bash:
          # - release event → use the release tag (e.g. v1.2.3)
          # - manual run with input → use inputs.tag
          # - otherwise → short SHA tag
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "value=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [[ -n "${{ inputs.tag }}" ]]; then
            echo "value=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context:   ${{ matrix.context }}
          file:      ${{ matrix.dockerfile }}                 # pick specific Dockerfile
          platforms: ${{ matrix.platforms }}                  # e.g., linux/amd64 or add linux/arm64
          push: true
          tags: ${{ env.IMAGE }}:${{ steps.tag.outputs.value }}-${{ matrix.suffix }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

      - name: Show published image
        run: echo "Pushed: ${{ env.IMAGE || 'default-image' }}"
        run: echo "Pushed: ${{ env.IMAGE }}:${{ steps.tag.outputs.value }}-${{ matrix.suffix }}"
